name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # 触发分支按需修改

env:
  REGISTRY: docker.io # 默认 Docker Hub，私有仓库需修改(如 registry.cn-hangzhou.aliyuncs.com)
  IMAGE_NAME: chb2024/blog

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub 用户名
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub 需用 PAT 令牌(非密码)

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # 如需多标签可添加：
          # tags: |
          #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
